import { Image } from 'react-grid-gallery'

export interface CustomImage extends Image {
  original: string
}

export const images: CustomImage[] = [
  {
    src: '/Images/GalleryImages/IMG_3089.jpeg',
    original: '/Images/GalleryImages/IMG_3089.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3090.jpeg',
    original: '/Images/GalleryImages/IMG_3090.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3091.jpeg',
    original: '/Images/GalleryImages/IMG_3091.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3103.jpeg',
    original: '/Images/GalleryImages/IMG_3103.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3104.jpeg',
    original: '/Images/GalleryImages/IMG_3104.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3107.jpeg',
    original: '/Images/GalleryImages/IMG_3107.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3109.jpeg',
    original: '/Images/GalleryImages/IMG_3109.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3110.jpeg',
    original: '/Images/GalleryImages/IMG_3110.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3116.jpeg',
    original: '/Images/GalleryImages/IMG_3116.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3124.jpeg',
    original: '/Images/GalleryImages/IMG_3124.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3133.jpeg',
    original: '/Images/GalleryImages/IMG_3133.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3138.jpeg',
    original: '/Images/GalleryImages/IMG_3138.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3141.jpeg',
    original: '/Images/GalleryImages/IMG_3141.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3142.jpeg',
    original: '/Images/GalleryImages/IMG_3142.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3145.jpeg',
    original: '/Images/GalleryImages/IMG_3145.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3146.jpeg',
    original: '/Images/GalleryImages/IMG_3146.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3152.jpeg',
    original: '/Images/GalleryImages/IMG_3152.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3159.jpeg',
    original: '/Images/GalleryImages/IMG_3159.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3160.jpeg',
    original: '/Images/GalleryImages/IMG_3160.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3162.jpeg',
    original: '/Images/GalleryImages/IMG_3162.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3781.jpeg',
    original: '/Images/GalleryImages/IMG_3781.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3784.jpeg',
    original: '/Images/GalleryImages/IMG_3784.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3785.jpeg',
    original: '/Images/GalleryImages/IMG_3785.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3787.jpeg',
    original: '/Images/GalleryImages/IMG_3787.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3796.jpeg',
    original: '/Images/GalleryImages/IMG_3796.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3800.jpeg',
    original: '/Images/GalleryImages/IMG_3800.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3810.jpeg',
    original: '/Images/GalleryImages/IMG_3810.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3814.jpeg',
    original: '/Images/GalleryImages/IMG_3814.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3816.jpeg',
    original: '/Images/GalleryImages/IMG_3816.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3818.jpeg',
    original: '/Images/GalleryImages/IMG_3818.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3820.jpeg',
    original: '/Images/GalleryImages/IMG_3820.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3822.jpeg',
    original: '/Images/GalleryImages/IMG_3822.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3825.jpeg',
    original: '/Images/GalleryImages/IMG_3825.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3826.jpeg',
    original: '/Images/GalleryImages/IMG_3826.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3828.jpeg',
    original: '/Images/GalleryImages/IMG_3828.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3830.jpeg',
    original: '/Images/GalleryImages/IMG_3830.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3834.jpeg',
    original: '/Images/GalleryImages/IMG_3834.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3860.jpeg',
    original: '/Images/GalleryImages/IMG_3860.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3861.jpeg',
    original: '/Images/GalleryImages/IMG_3861.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3862.jpeg',
    original: '/Images/GalleryImages/IMG_3862.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3864.jpeg',
    original: '/Images/GalleryImages/IMG_3864.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_3870.jpeg',
    original: '/Images/GalleryImages/IMG_3870.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6422.jpeg',
    original: '/Images/GalleryImages/IMG_6422.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6427.jpeg',
    original: '/Images/GalleryImages/IMG_6427.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6428.jpeg',
    original: '/Images/GalleryImages/IMG_6428.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6435.jpeg',
    original: '/Images/GalleryImages/IMG_6435.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6599.jpeg',
    original: '/Images/GalleryImages/IMG_6599.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6600.jpeg',
    original: '/Images/GalleryImages/IMG_6600.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6611.jpeg',
    original: '/Images/GalleryImages/IMG_6611.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6613.jpeg',
    original: '/Images/GalleryImages/IMG_6613.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6618.jpeg',
    original: '/Images/GalleryImages/IMG_6618.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6628.jpeg',
    original: '/Images/GalleryImages/IMG_6628.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6640.jpeg',
    original: '/Images/GalleryImages/IMG_6640.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6643.jpeg',
    original: '/Images/GalleryImages/IMG_6643.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6646.jpeg',
    original: '/Images/GalleryImages/IMG_6646.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6653.jpeg',
    original: '/Images/GalleryImages/IMG_6653.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6662.jpeg',
    original: '/Images/GalleryImages/IMG_6662.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6664.jpeg',
    original: '/Images/GalleryImages/IMG_6664.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6669.jpeg',
    original: '/Images/GalleryImages/IMG_6669.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6671.jpeg',
    original: '/Images/GalleryImages/IMG_6671.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6673.jpeg',
    original: '/Images/GalleryImages/IMG_6673.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6674.jpeg',
    original: '/Images/GalleryImages/IMG_6674.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6675.jpeg',
    original: '/Images/GalleryImages/IMG_6675.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6677.jpeg',
    original: '/Images/GalleryImages/IMG_6677.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6678.jpeg',
    original: '/Images/GalleryImages/IMG_6678.jpeg',
    width: 600,
    height: 800,
  },
  {
    src: '/Images/GalleryImages/IMG_6680.jpeg',
    original: '/Images/GalleryImages/IMG_6680.jpeg',
    width: 600,
    height: 800,
  },
]
